// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// tpm2
arma::mat tpm2(const arma::mat z, const arma::mat P, const arma::mat Phi);
RcppExport SEXP SpatPCA_tpm2(SEXP zSEXP, SEXP PSEXP, SEXP PhiSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Phi(PhiSEXP);
    __result = Rcpp::wrap(tpm2(z, P, Phi));
    return __result;
END_RCPP
}
// spatpcacv2_rcpp
List spatpcacv2_rcpp(NumericMatrix sxyr, NumericMatrix Yr, int M, int K, NumericVector tau1r, NumericVector tau2r, NumericVector gammar, NumericVector nkr, int maxit, double tol, NumericVector l2r);
RcppExport SEXP SpatPCA_spatpcacv2_rcpp(SEXP sxyrSEXP, SEXP YrSEXP, SEXP MSEXP, SEXP KSEXP, SEXP tau1rSEXP, SEXP tau2rSEXP, SEXP gammarSEXP, SEXP nkrSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP l2rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type sxyr(sxyrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau1r(tau1rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2r(tau2rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammar(gammarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nkr(nkrSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l2r(l2rSEXP);
    __result = Rcpp::wrap(spatpcacv2_rcpp(sxyr, Yr, M, K, tau1r, tau2r, gammar, nkr, maxit, tol, l2r));
    return __result;
END_RCPP
}
// eigenest_rcpp
List eigenest_rcpp(NumericMatrix phir, NumericMatrix Yr, double gamma, NumericMatrix phi2r);
RcppExport SEXP SpatPCA_eigenest_rcpp(SEXP phirSEXP, SEXP YrSEXP, SEXP gammaSEXP, SEXP phi2rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type phir(phirSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi2r(phi2rSEXP);
    __result = Rcpp::wrap(eigenest_rcpp(phir, Yr, gamma, phi2r));
    return __result;
END_RCPP
}
