# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#'
#' Internal function: Set the number of cores for parallel computing
#'
#'
#' @keywords internal
#' @param maxit Number of number of cores for parallel computing.
#' @return Logical
#' 
set_cores <- function(ncores = NULL) {
  if (!is.null(ncores)) {
    if (!is.numeric(ncores))
      stop("Please enter valid type - but got ", class(ncores))
    if (ncores > 1) {
      tryCatch({
        RcppParallel::setThreadOptions(numThreads = ncores)
      }, error = print)
    } else {
      stop("The number of cores is not greater than 1 - but got ", ncores)
    }
  }
}
