# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tpmatrix <- function(P) {
    .Call(`_SpatPCA_tpmatrix`, P)
}

tpm2 <- function(z, P, Phi) {
    .Call(`_SpatPCA_tpm2`, z, P, Phi)
}

spatpcaCV <- function(sxyr, Yr, M, K, tau1r, tau2r, gammar, nkr, maxit, tol, l2r) {
    .Call(`_SpatPCA_spatpcaCV`, sxyr, Yr, M, K, tau1r, tau2r, gammar, nkr, maxit, tol, l2r)
}

eigenEstimate <- function(phir, Yr, gamma, phi2r) {
    .Call(`_SpatPCA_eigenEstimate`, phir, Yr, gamma, phi2r)
}

